// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {photo} from '../models';
import {config} from '../models';

export function DeletePhoto(arg1:string,arg2:string):Promise<void>;

export function DeletePhotos(arg1:Array<string>,arg2:string):Promise<void>;

export function GetCurrentLocation():Promise<main.CurrentLocation>;

export function ListPhotos(arg1:string):Promise<Array<photo.Item>>;

export function LoadSettings():Promise<config.Settings>;

export function PhotoDataURL(arg1:string,arg2:string):Promise<string>;

export function ReverseGeocode(arg1:number,arg2:number):Promise<main.LocationDetails>;

export function SavePhoto(arg1:main.SaveRequest):Promise<photo.Item>;

export function SaveSettings(arg1:config.Settings):Promise<void>;

export function SelectOutputFolder(arg1:string):Promise<string>;

export function ShowPhoto(arg1:string,arg2:string):Promise<void>;

export function Thumbnail(arg1:string,arg2:string):Promise<string>;
