// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeletePhoto(arg1, arg2) {
  return window['go']['main']['App']['DeletePhoto'](arg1, arg2);
}

export function DeletePhotos(arg1, arg2) {
  return window['go']['main']['App']['DeletePhotos'](arg1, arg2);
}

export function GetCurrentLocation() {
  return window['go']['main']['App']['GetCurrentLocation']();
}

export function ListPhotos(arg1) {
  return window['go']['main']['App']['ListPhotos'](arg1);
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function PhotoDataURL(arg1, arg2) {
  return window['go']['main']['App']['PhotoDataURL'](arg1, arg2);
}

export function ReverseGeocode(arg1, arg2) {
  return window['go']['main']['App']['ReverseGeocode'](arg1, arg2);
}

export function SavePhoto(arg1) {
  return window['go']['main']['App']['SavePhoto'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectOutputFolder(arg1) {
  return window['go']['main']['App']['SelectOutputFolder'](arg1);
}

export function ShowPhoto(arg1, arg2) {
  return window['go']['main']['App']['ShowPhoto'](arg1, arg2);
}

export function Thumbnail(arg1, arg2) {
  return window['go']['main']['App']['Thumbnail'](arg1, arg2);
}
